### ISSUE TITLE
🐛 home - delete/edit/share 후 경로 이동 후 돌아오면 이전 데이터로 렌더링 됨

### ISSUE THREAD

**Issue by KimHayeon1** [NeedsLap/MOMOO-Nextjs#126]
### Description
**delete/edit**
  - 원인: albumData를 변경하지 않고, 자식 컴포넌트(Album)의 data를 변경함/refresh하지 않았음
 
**share**
- 원인
  1. share 후 albumData의 해당 album.sharedUser는 변하지 않기 때문에, isShared 초깃값이 이전 data로 할당됨
  -> isShared를 제거한 로직에서 버그가 사라지지 않음
  2. 브라우저 이전/다음 버튼으로 경로 이동 후 돌아오면, Home 컴포넌트 useEffect(() => {}, []) 내 fetch를 실행하지 않고, 캐싱되어 있는 데이터를 사용함
  -> share 후 router.refresh() (실패)
  -> cache: 'no-store' (성공)
- 해결: 캐싱은 그대로 유지하고, 공유 앨범이 변경될 때만 다시 fetch

### To-do
- [x] delete/edit 후 albumData 변경
- [x] add/delete/edit 후 refresh
- [x] 공유 앨범이 변경될 때 다시 fetch
