### ISSUE TITLE
💡 앨범 공유

### ISSUE THREAD

**Issue by KimHayeon1** [NeedsLap/MOMOO-Nextjs#8]
### Description
- home: 공유한 사용자 displayname 불러와서 렌더링
  - signup/edit-profile: displayname 필수 항목으로 변경
  - 기존 회원 중, displayname이 없는 경우 email로 표시
- sharedAlbums - 내가 공유한 앨범 추가
- 공유 모달: 본인 검색 시 예외처리
- GET album/sharing: 생성한 날짜순으로 정렬
- home: 공유 앨범 추가/삭제 시, sharedAlbums 업데이트

### To-do
- [x] home - displayname 렌더링
- [x] signup/edit profile - displayname 필수 항목으로 변경
- [x] sharedAlbums: 내가 공유한 앨범 추가
  - [x] POST album/sharing/:uid: 공유한 사용자의 sharedAlbums에 해당 앨범 ref 추가(sharedAlbums에  해당 앨범 ref가 없는 경우)
  - [x] DELETE album/sharing/:uid: 해당 앨범의 sharedUsers.length === 0이라면, 공유한 사용자의 sharedAlbums에서 해당 앨범 ref 삭제
  - [x] DELETE album/id: 공유한 사용자의 sharedAlbums에서 해당 앨범 ref 삭제
  - [x] home - 공유 앨범 - '내가 생성'
- [x] 공유 모달: 본인 검색 시
- [x] GET album/sharing: 생성한 날짜순으로 정렬
- [x] home: 공유 앨범 추가/삭제 시, sharedAlbums 업데이트

### ETC
[#253](https://github.com/yonainthefish/MoMoo/issues/253) 이어서 작성
